<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FT.Domain\FT.Domain.csproj" />
    <ProjectReference Include="..\FT.Infrastructure\FT.Infrastructure.csproj" />
    <ProjectReference Include="..\FT.Utils\FT.Utilities.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Commons\" />
    <Folder Include="Validators\User\" />
  </ItemGroup>

</Project>
